### ISSUE TITLE
[Codebundle] Mongodb Healthcheck

### ISSUE THREAD

**Issue by jon-funk** [runwhen-contrib/codecollection-authors#27]
**Scope**
Healthcheck a mongodb instance and return a value of 1 when healthy or 0 if unhealthy

**Requested By (Optional)**
- RunWhen

**Related Integrations**
- Kubernetes

**Definition of Done**
- [x] Codebundle Implementation accomplishes scope (or provide a justification for why it may differ)
- [x] Attach a screenshot of the codebundle pushing a metric locally (if an SLI) or showing a report (if a taskset)
- [x] Attach a screenshot of the SLI or Taskset running in a workspace.

**Optional Comments**
- Assume exists within a k8s cluster

**Comment by stewartshea** [comment]
https://github.com/runwhen-contrib/rw-public-codecollection/tree/main/codebundles/mongodb-health-gcp-promql

![Image](https://user-images.githubusercontent.com/18314168/228925737-cbdd106c-3056-42ca-b983-0f72c100b421.png)


![Image](https://user-images.githubusercontent.com/18314168/228925823-179f1164-e530-4240-a921-03860d4aa416.png)
